# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

expand_cluster <- function(K, inactive_clus, active_clus, old_assign, psi, xi, a_theta, b_theta) {
    .Call(`_ClusterProj_expand_cluster`, K, inactive_clus, active_clus, old_assign, psi, xi, a_theta, b_theta)
}

contract_cluster <- function(K, active_clus, old_assign, psi, xi, a_theta, b_theta) {
    .Call(`_ClusterProj_contract_cluster`, K, active_clus, old_assign, psi, xi, a_theta, b_theta)
}

expand_contract <- function(K, old_assign, psi, xi, a_theta, b_theta) {
    .Call(`_ClusterProj_expand_contract`, K, old_assign, psi, xi, a_theta, b_theta)
}

cluster_assign <- function(clus_assign, clus_hyper, y, data_hyper) {
    .Call(`_ClusterProj_cluster_assign`, clus_assign, clus_hyper, y, data_hyper)
}

test_fn <- function(probs) {
    .Call(`_ClusterProj_test_fn`, probs)
}

foo <- function(t, k) {
    .Call(`_ClusterProj_foo`, t, k)
}

