# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

expand_step <- function(K, old_assign, alpha, xi, a_theta, b_theta) {
    .Call(`_ClusterProj_expand_step`, K, old_assign, alpha, xi, a_theta, b_theta)
}

cluster_assign <- function(K, old_assign, xi, y, gamma_hyper, alpha) {
    .Call(`_ClusterProj_cluster_assign`, K, old_assign, xi, y, gamma_hyper, alpha)
}

split_merge <- function(K, old_assign, psi, xi, y, gamma_hyper, a_theta, b_theta) {
    .Call(`_ClusterProj_split_merge`, K, old_assign, psi, xi, y, gamma_hyper, a_theta, b_theta)
}

cluster_func <- function(K, old_assign, psi, xi, y, gamma_hyper, a_theta, b_theta, iter = 1000L) {
    .Call(`_ClusterProj_cluster_func`, K, old_assign, psi, xi, y, gamma_hyper, a_theta, b_theta, iter)
}

test_fn <- function(probs) {
    .Call(`_ClusterProj_test_fn`, probs)
}

foo <- function(t, k) {
    .Call(`_ClusterProj_foo`, t, k)
}

test_List <- function(test_1) {
    .Call(`_ClusterProj_test_List`, test_1)
}

