# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

density_gamma <- function(yi, gamma_k) {
    .Call(`_ClusterProj_density_gamma`, yi, gamma_k)
}

allocate_prob <- function(i, current_assign, xi, y, gamma_hyper, active_clus) {
    .Call(`_ClusterProj_allocate_prob`, i, current_assign, xi, y, gamma_hyper, active_clus)
}

sample_clus <- function(norm_probs, active_clus) {
    .Call(`_ClusterProj_sample_clus`, norm_probs, active_clus)
}

expand_step <- function(K, old_assign, alpha, xi, a_theta, b_theta) {
    .Call(`_ClusterProj_expand_step`, K, old_assign, alpha, xi, a_theta, b_theta)
}

cluster_assign <- function(K, old_assign, xi, y, gamma_hyper, alpha) {
    .Call(`_ClusterProj_cluster_assign`, K, old_assign, xi, y, gamma_hyper, alpha)
}

split_merge <- function(K, old_assign, alpha, xi, y, gamma_hyper, a_theta, b_theta, T_iter = 10L) {
    .Call(`_ClusterProj_split_merge`, K, old_assign, alpha, xi, y, gamma_hyper, a_theta, b_theta, T_iter)
}

cluster_func <- function(K, old_assign, alpha, xi, y, gamma_hyper, a_theta, b_theta, sm_iter = 10L, all_iter = 100L) {
    .Call(`_ClusterProj_cluster_func`, K, old_assign, alpha, xi, y, gamma_hyper, a_theta, b_theta, sm_iter, all_iter)
}

